# SPDX-FileCopyrightText: Copyright (c) 2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI Pipeline
run-name: CI Pipeline

on:
  workflow_call:
    inputs:
      container:
        description: 'The container to use for all CI stages'
        required: true
        type: string
      pr_info:
        description: 'The JSON string containing the PR information'
        required: true
        type: string
      base_sha:
        description: 'The base SHA of the PR'
        required: true
        type: string

# We only support ubuntu, so bash is the default
defaults:
  run:
    shell: bash

env:
  GH_TOKEN: "${{ github.token }}"
  GIT_COMMIT: "${{ github.sha }}"
  BASE_SHA: "${{ inputs.base_sha }}"
  RAPIDS_CONDA_RETRY_MAX: "5"
  WORKSPACE: "${{ github.workspace }}/agentiq"
  WORKSPACE_TMP: "${{ github.workspace }}/tmp"
  UV_CACHE_DIR: .uv-cache

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  discussions: none
  id-token: write
  issues: none
  packages: read
  pages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  check:
    name: Check
    runs-on: linux-amd64-cpu4
    timeout-minutes: 15
    container:
      image: ${{ inputs.container }}
    strategy:
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'agentiq'

      - name: Check
        shell: bash
        run: ./agentiq/ci/scripts/github/checks.sh

  test:
    name: Test
    needs: [check]
    runs-on:  linux-${{ matrix.arch }}-cpu4
    timeout-minutes: 30
    container:
      image: ${{ inputs.container }}
    strategy:
      fail-fast: true
      matrix:
        arch: ["amd64", "arm64"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          path: 'agentiq'

      - name: Test:linux:${{ matrix.arch }}
        shell: bash
        run: ./agentiq/ci/scripts/github/tests.sh

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        # Upload test results even if the tests fail
        if: ${{ always() }}
        with:
          name: "test-results-${{ matrix.arch }}"
          path: "${{ github.workspace }}/tmp/*.xml"
          if-no-files-found: error


  documentation:
    name: Documentation
    needs: [check]
    runs-on: linux-amd64-cpu4
    timeout-minutes: 15
    container:
      image: ${{ inputs.container }}
    strategy:
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          path: 'agentiq'

      - name: build_docs
        shell: bash
        run: ./agentiq/ci/scripts/github/docs.sh

      - name: Upload Documentation
        uses: actions/upload-artifact@v4
        with:
          name: "docs"
          path: "${{ github.workspace }}/tmp/docs.tar.bz2"
          if-no-files-found: error
          compression-level: 0


  package:
    name: Build Wheels
    needs: [check]
    runs-on: linux-amd64-cpu4
    timeout-minutes: 60
    container:
      image: ${{ inputs.container }}
    strategy:
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          path: 'agentiq'

      - name: build_wheels
        shell: bash
        run: ./agentiq/ci/scripts/github/build_wheel.sh

      - name: Upload Wheels
        uses: actions/upload-artifact@v4
        with:
          name: "wheels"
          path: "${{ github.workspace }}/tmp/wheels/**/*.whl"
          if-no-files-found: error
          compression-level: 9
